### ISSUE TITLE
Fragen zum Workshop

### ISSUE THREAD

**Issue by Flatric** [Fuenfgeld/2022TeamBDataEngineeringBC#13]
- Bis wann muss der Workshop fertig sein?
- Vorgesehene Dauer des Workshops (inkl. Bearbeitungszeit für die Übungen)?
- Form des Workshops? (Livepräsentation mit Pausen für Übungen? Nur Theorie? Aufgezeichnetes Video?)
- Wie viele Teilnehemer pro Gruppe präsentieren?

**Comment by Fuenfgeld** [comment]
* Bis wann muss der Workshop fertig sein? 
* #### 05.05 Donnerstag
* Vorgesehene Dauer des Workshops (inkl. Bearbeitungszeit für die Übungen)?
* #### ca 60 min (kann auch ein bisschen überziehen)
* Form des Workshops? (Livepräsentation mit Pausen für Übungen? Nur Theorie? Aufgezeichnetes Video?)
* #### Nicht nur Theorie, es muss praktisch sein, der Rest bleibt euch überlassen.
* Wie viele Teilnehemer pro Gruppe präsentieren?
* #### Alle
